<div class="pageHeader">
    <form id="pagerForm" action="<?php echo $this->url('information',array('controller'=>'user','action'=>'list'));?>"   method="post"  onSubmit='return navTabSearch(this);'>
     <input type="hidden" name="pageNum" 		value="1" />
	 <input type="hidden" name="numPerPage" 	value="<?php echo $this->numPerPage;?>" />
	 <table class="searchContent">
        <tr>
            <td><label>用户编号：</label></td>
            <td><input type="text" name="userId"  value="<?php echo $this->userId;?>"/>
            <td><label>用户名称：</label></td>
            <td><input type="text" name="nameStr" value="<?php echo $this->nameStr;?>"/></td>
            <td><label>所在部门：</label></td>
            <td><select name="departmentId"  >
				        <option value="">请选择部门</option>
				</select>
			</td>
            <td><input type="submit" value='点击查询' /></td>
        </tr>
     </table>
	</form>
</div>
<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add"    href="<?php echo $this->url('information',array('controller'=>'user','action'=>'add'));?>" target="navTab" title="添加用户" rel='showUserAdd' ><span>添加用户</span></a></li>
			<li><a class="delete" href="<?php echo $this->url('information',array('controller'=>'user','action'=>'delete'));?>?id={id}" target="ajaxTodo" title="确定要删除吗?"><span>删除用户</span></a></li>
			<li><a class="edit"   href="<?php echo $this->url('information',array('controller'=>'user','action'=>'edit'));?>?id={id}" target="navTab" title="编辑用户" rel={id} ><span>修改用户</span></a></li>
		</ul>
	</div>
	<table class="table" width="99%"  layoutH="113" targetType="navTab">
		<thead>
			<tr>
			    <th align='center' width="40">编号</th>
				<th align='center'>用户名</th>
				<th align='center' width="160">所属学校</th>
				<th align='center' width="100">生日</th>
				<th align='center' width="140">工作类型</th>
				<th align='center' width="140">主讲科目</th>
				<th align='center' width="160">创建时间</th>
				<th align='center' width="100">用户状态</th>
			</tr>
		</thead>
		<tbody>
		    <?php foreach ($list as $user):?>
			<tr target="id" rel="<?php echo $user['id']; ?>">
			    <td><?php echo $user['id'];?></td>
				<td><?php echo $user['realname'];?></td>
				<td><?php echo $user['school_id_string'];?></td>
				<td><?php echo $user['birthday'];?></td>
				<td><?php echo $user['work_type_id_string'];?></td>
				<td><?php echo $user['subject_id_string'];?></td>
				<td><?php echo $user['add_time'];?></td>
				<td><?php echo $user['status_string'];?></td>
			</tr>
		    <?php endforeach;?>
		</tbody>
	</table>
	<div class="panelBar">
		<div class="pages">
			<span>显示</span>
			<select class="combox" name="numPerPage" onchange="navTabPageBreak({numPerPage:this.value})">
				<option value="20" <?php if ($numPerPage==20): echo 'selected="selected"';endif;?>>20</option>
				<option value="50" <?php if ($numPerPage==50): echo 'selected="selected"';endif;?>>50</option>
				<option value="100" <?php if ($numPerPage==100): echo 'selected="selected"';endif;?>>100</option>
				<option value="200" <?php if ($numPerPage==200): echo 'selected="selected"';endif;?>>200</option>
			</select>
			<span>条，共<?php echo $totalCount;?>条</span>
		</div>		
		<div class="pagination" 
		    targetType="navTab"
		    totalCount="<?php echo $totalCount;?>" 
		    numPerPage="<?php echo $numPerPage;?>" 
		    pageNumShow="<?php echo $pageNumShow;?>" 
		    currentPage="<?php echo $pageNum;?>">
		</div>
	</div>
</div>