<div class="pageHeader">
	<?php echo  $this->form()->openTag($pagerForm);?>
	<?php foreach($pagerForm as $key=>$element):?>
	    <?php if($element->getAttribute('type')=='hidden'):?>
	    
	    <?php echo $this->formElement($element);$pagerForm->remove( $element->getName() );?>
	    
	    <?php endif;?>
	<?php endforeach;?>
	
	<table  class='pagerTable'  cellspacing='0'  cellpadding='0' border='0'>
	<tbody>
	<?php 
		$formElementList = $pagerForm->getElements();
		$formElementList = array_chunk($formElementList,$lookupConfig['pager_form']['row_element_count']);
	?>
	<?php foreach($formElementList as $rowKey=>$row):?>
	 	<tr>
	 		<?php foreach($row as $element):?>
	 		<?php if($element->hasAttribute('notRenderLabel')):?>
	 			<td class='center'>&nbsp;</td>
	 		<?php else:?>
	 			<td class='center'><?php echo $element->getLabel(); ?></td>
	 		<?php endif;?>
	 		<td class='center'><?php echo $this->formElement($element);?></td>
			<?php endforeach;?>
	 	</tr>
	<?php endforeach;?>
	</tbody>
	</table>
	<?php echo $this->form()->closeTag();?>
</div><!-- pageHeader end -->
<div class="pageContent">
	<table class="table" width="100%"  layoutH="<?php echo $lookupConfig['layout_height'];?>">
		<thead>
			<tr>
				<th width='25'>&nbsp;</th>
			    <?php foreach($templateDisplayColumns as $columnName=>$columnSetting):?>
			    	<?php if(isset($columnSetting['width'])):?>
			    		<th width="<?php echo $columnSetting['width'];?>" align='center'><?php echo $columnSetting['label'];?></th>
					<?php else:?>
			    		<th align='center'><?php echo $columnSetting['label'];?></th>
					<?php endif;?>
			    <?php endforeach;?>
			</tr>
		</thead>
		<tbody>
			
			<?php foreach($list as $key=>$element ):?>
		    <tr target="id" rel="<?php echo $element['id'];?>">
		        <td>
		        	<?php if($selectControlType=='checkbox'):?>
	       				<input type='checkbox' name='group'   value="<?php echo sprintf("{'%s':'%s','name':'%s'}",$formElement,$element['id'],$element['name']);?>"  />
				    <?php elseif($selectControlType=='radio'):?>
				        <input type='radio'    name='group'   value="<?php echo sprintf("{'%s':'%s','name':'%s'}",$formElement,$element['id'],$element['name']);?>"  />
				    <?php endif;?>
		        </td>
		        <?php foreach($templateDisplayColumns as $columnName=>$columnSetting):?>
		        		<td><?php echo $element[$columnName];?></td>
		        <?php endforeach;?>
		    </tr>
			<?php endforeach;?>
		</tbody>
	</table>
	
	<div class="panelBar" >
        <div class="pages">
            <span>显示</span>
            <?php echo $this->formSelect($paginationForm->get('pageRowCount'));?>
			<span>条，共<?php echo $lookupConfig['count'];?>条</span>
        </div><!--pages end -->
        <div class="pagination" 
        	 targetType="dialog" 
        	 totalCount="<?php echo $lookupConfig['count'];?>" 
        	 numPerPage="<?php echo $lookupConfig['pageRowCount'];?>" 
        	 pageNumShown="5" 
        	 currentPage="<?php echo $lookupConfig['currentPageNumber'];?>">
        </div>
     </div><!-- panelBar end -->
</div><!-- pageContent end -->