<div class="pageContent">
	<table class="table" width="100%"  layoutH="45" targetType="navTab" source='<?php echo $this->source;?>'  form_element='<?php echo $this->formElement;?>' page_type='<?php echo $this->pageType;?>' PostURL='<?php echo $this->postUrl;?>'>
		<thead>
			<tr>
			  <?php foreach($templateDisplayColumns as $columnName=>$columnSetting):?>
			    	<?php if($columnName=='name'):?>
			    		<th align='center'><?php echo $columnSetting['label'];?></th>
					<?php else:?>
			    		<th width="<?php echo $columnSetting['width'];?>" align='center'><?php echo $columnSetting['label'];?></th>
					<?php endif;?>
			    <?php endforeach;?>	
			</tr>
		</thead>
		<tbody>
		    	<?php echo $this->list;?>
		</tbody>
	</table>
</div><!-- pageContent end -->
<div class="panelBar">
	<input  type="button" multLookup="group" warn="请至少选择一个对象"  value='确认选择' /></li>
</div>



