<div id="weixin-modal-dialog" class="modal fade bs-modal-lg in"  aria-hidden="false">
	<div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">关注微信公众号</h4>
            </div>
            <div class="modal-body">
            	<img width='258' height='258' src='<?php echo $this->qrCodePath;?>' />
            </div>
            <div class="modal-footer">
            	1、您可通过在微信通讯录搜索康润律师事务所，即可关注。<br/>
            	2、扫描上方二维码添加。
            </div>
 	</div><!--modal-content-->
 </div><!--weixin-modal-dialog  -->