<?php foreach($list as $key=>$element ):?>
	<tr target="id" rel="<?php echo $element['id'];?>" class='unlimitedList' left_number="<?php echo $element['left_number'];?>"  right_number="<?php echo $element['right_number'];?>" level="<?php echo $element['level'];?>" parent_id="<?php echo $element['parent_id'];?>">
        <td><?php echo $element['id'];?></td>
        <td><div class='item'><?php echo $element['name'];?></div></td>
        <td><?php echo $element['level'];?></td>
        <td><?php echo $element['children_count'];?></td>
        <td><?php echo $element['status_string'];?></td>
	</tr>
<?php endforeach;?>
