<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" 	  href="<?php echo $this->url('information',array('controller'=>'role','action'=>'add'));?>" 				target="navTab"   rel="add"><span>添加角色</span></a></li>
			<li><a class="delete" href="<?php echo $this->url('information',array('controller'=>'role','action'=>'delete'));?>?id={id}"		target="ajaxTodo" title="确定要删除吗?"><span>删除角色</span></a></li>
			<li><a class="edit"   href="<?php echo $this->url('information',array('controller'=>'role','action'=>'edit'));?>?id={id}"    	target="navTab"   rel="edit" ><span>修改角色</span></a></li>
		 </ul>
	</div>
	<table class="table" width="100%"  layoutH="115" targetType="navTab" PostURL='<?php echo $this->url('information',array('controller'=>'role','action'=>'ajaxGetUnlimitedRowList'));?>'>
		<thead>
			<tr>
			    <th width="60" align='center'>编号</th>
				<th align='center'>分类名称</th>
				<th width="100" align='center'>分类级别</th>
				<th width="100" align='center'>子分类数量</th>
				<th width="100" align='center'>分类状态</th>
			</tr>
		</thead>
		<tbody>
		    <?php foreach($list as $key=>$element ):?>
		    <tr target="id" rel="<?php echo $element['id'];?>" class='unlimitedList' left_number="<?php echo $element['left_number'];?>"  right_number="<?php echo $element['right_number'];?>" level="<?php echo $element['level'];?>" parent_id="<?php echo $element['parent_id'];?>">
		        <td><?php echo $element['id'];?></td>
		        <td><div class='item'><?php echo $element['name'];?></div></td>
		        <td><?php echo $element['level'];?></td>
		        <td><?php echo $element['children_count'];?></td>
		        <td><?php echo $element['status_string'];?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>