<div class="pageContent">
	<?php echo  $this->form()->openTag($CustomerConfigForm);?>
	<table  id='FrontendConfigTable' width='100%' class='CustomerTable'  layoutH='26'>
		<?php foreach($CustomerConfigForm as $ConfigElement):?>
	    <tr>
	 	    <td class='center' width='140'><?php echo $ConfigElement->getLabel(); ?></td>
			<td class='indent' width='200'><?php echo $this->formElement($ConfigElement);?></td>
			<td class='center' ><?php echo $ConfigElement->getInfo(); ?></td>
		</tr>
	  	<?php endforeach;?>
	</table>
	<div class="panelBar">
		    <ul class="toolBar">
				<li><input type='submit' value='保存修改' /></li>
			</ul>
	</div>
	<?php echo $this->form()->closeTag();?>
</div><!-- pageContent end -->