<div id='BannerPictureContainer'>
	<?php echo $this->topBannerViewModel;?>
</div><!-- BannerPictureContainer end -->
<table id='ColumnsLayoutTable' border="0" cellspacing='0' cellpadding='0' >
	<tr>
		<td valign='top'>
			<?php echo $this->articleCategorySidebarViewModel;?>
		</td>
		<td colspan='2' valign='top'>
			<table cellspacing='0' cellpadding='0'>
				<tr>
					<td><div id='SmallSlidePictureContainer'></div></td>
					<td><div id='SideArticleColumn'><?php echo $this->sideArticleColumnViewModel;?></div></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td valign='top'><div id='SidebarPhoneNumber'></div></td>
		<td valign='top' rowspan='2'>
			<div class='EqualArticleColumn'>
				<?php echo $this->leftArticleColumnViewModel;?>
			</div><!-- EqualArticleColumn end -->
		</td>
		<td valign='top' rowspan='2'>
			<div class='EqualArticleColumn'>
				<?php echo $this->rightArticleColumnViewModel;?>
			</div><!-- EqualArticleColumn end -->
		</td>
	</tr>
	<tr>
		<td valign='top'><div id='SidebarActivity'></div></td>
	</tr>
</table>


