<div id='BannerPictureContainer'>
	<?php echo $this->topBannerViewModel;?>
</div><!-- BannerPictureContainer end -->
<table id='ColumnsLayoutTable' border="0" cellpadding='0' cellspacing='0'>
	<tr>
		<td width='231' rowspan='2'>
			<?php echo $this->articleCategorySidebarViewModel;?>
		</td>
		<td colspan='2' height="50">&nbsp;</td>
	</tr>
	<tr>
		<td colspan='2'>
			<div id='SmallSlidePictureContainer'></div>
			<div id='SideArticleColumn'><?php echo $this->sideArticleColumnViewModel;?></div>
		</td>
	</tr> 
	<tr>
		<td><div id='SidebarPhoneNumber'></div></td>
		<td rowspan='2'>
			<div class='EqualArticleColumn'>
				<?php echo $this->leftArticleColumnViewModel;?>
			</div><!-- EqualArticleColumn end -->
		</td>
		<td rowspan='2'>
			<div class='EqualArticleColumn'>
				<?php echo $this->rightArticleColumnViewModel;?>
			</div><!-- EqualArticleColumn end -->
		</td>
	</tr>
	<tr>
		<td><div id='SidebarActivity'></div></td>
	</tr>
</table>


