<div class='slide-javascript-control'>
	<a href="javascript:;" class="btn-previous" >&nbsp;</a> 
	<a href="javascript:;" class="btn-next"     >&nbsp;</a>
	<table cellpadding='0' cellspacing='0'>
		<tr>
		<?php foreach($this->slideElementList as $element):?>	
			<td>
				<div class="slider-item" style='width:984px;'>
					<img src='<?php echo $element->imagePath;?>' width='984' height='313' />
					<div class="background">
						<div class='title'><?php echo $element->title;?></div>
						<div class='description'><?php echo $element->description;?></div>
					</div>
				</div>
			</td>
		<?php endforeach;?>				
		</tr>
	</table>
</div>
<script type='text/javascript'>

	$(".slide-javascript-control").find('.btn-previous').click(function(){
		
		$(".slide-javascript-control table tbody").find('td:first').find('.slider-item').animate({width:'0px'},1000,function(){

			$(".slide-javascript-control table tbody").find('td:first').remove().appendTo( $(".slide-javascript-control table tbody tr"));

			$(".slide-javascript-control table tbody").find('td').find('.slider-item').css('width','984px');
			
		});

		
				


		

		
		
	});
</script>


