<ul class='article-column-ul'>
	<li class='ArticleCategoryName'><?php echo $this->categoryName; ?></li>
	<?php if(isset($this->articleList)):?>
		<?php foreach($this->articleList as $element):?>					
			<li>
				<a href='<?php echo $element['href']?>' target='_blank'><?php echo $element['title']; ?></a>
				<?php if($this->articleTitleWithDate):?>
					<span class='date'><?php echo $element['date']; ?></span>
				<?php endif;?>
			</li>		
		<?php endforeach;?>	
	<?php endif;?>
</ul>