	<?php echo  $this->form()->openTag($form);?>
	<?php foreach($form as $key=>$element):?>
    <?php if($element->getAttribute('type')=='hidden'):?>
    <?php echo $this->formElement($element);$form->remove( $element->getName() );?>
    <?php endif;?>
	<?php endforeach;?>

<div class="pageContent" layoutH='28'>

	<table id='UserAddTable' class='CustomerTable' width='100%' cellspacing='0'  cellpadding='0' border='0'>
	<tbody>
	<?php foreach($form as $key=>$element):?>
	 	<?php if(in_array(  $element->getName() , array('submit','reset','close') ))continue;?>
	    <tr>
	 	    <td class='center' width='140'><?php echo $element->getLabel(); ?></td>
			<td><?php echo $this->formElement($element);?></td>
		</tr>
	<?php endforeach;?>
	</tbody>
	</table>
</div><!-- pageContent end -->	
	

<div class="panelBar">
	<ul class="toolBar">
		<li><?php echo $this->formSubmit($form->get('submit'));?></li>
		<li><?php echo $this->formButton($form->get('reset'));?></li>
		<li><?php echo $this->formButton($form->get('close'));?></li>
	</ul>
</div>
<?php echo $this->form()->closeTag();?>
<script type='text/javascript'>


function onUploadSuccess(file, data, response) {
	
	 var data = eval("("+data+")");
	 var status   = data.status;//得到状态
	 var info     = data.info;//得到错误信息
	 var temp_name     = data.upload_flag;//得到上传到临时目录的文件名
	 
	 if(status){
		 alert(info);
		$("#upload_flag").attr('value',temp_name);
	 }
	 else{
		 alertMsg.error(info);
	 }
	 
}


</script>