<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<?php foreach($operationList as $operation):?>
				<li><a class="<?php echo $operation['class'];?>"
					   href="<?php echo $operation['url'];?>"
					   rel="<?php echo $operation['rel'];?>"
					   <?php if(isset($operation['target'])):?>
					   	   target="<?php echo $operation['target'];?>"  
					   <?php endif;?>
					 ><span><?php echo $operation['title'];?></span>
					</a>
			    </li>
			<?php endforeach;?>
		</ul>
	</div>
	<table class="table" width="100%"  layoutH="115" targetType="navTab" PostURL='<?php echo $this->postUrl;?>'>
		<thead>
			<tr>
			    <?php foreach($templateDisplayColumns as $columnName=>$columnSetting):?>
			    	<?php if($columnName=='name'):?>
			    		<th align='center'><?php echo $columnSetting['label'];?></th>
					<?php else:?>
			    		<th width="<?php echo $columnSetting['width'];?>" align='center'><?php echo $columnSetting['label'];?></th>
					<?php endif;?>
			    <?php endforeach;?>
			</tr>
		</thead>
		<tbody>
		    <?php foreach($list as $key=>$element ):?>
		    <tr target="id" rel="<?php echo $element['id'];?>" class='unlimitedList' left_number="<?php echo $element['left_number'];?>"  right_number="<?php echo $element['right_number'];?>" level="<?php echo $element['level'];?>" parent_id="<?php echo $element['parent_id'];?>">
		        <?php foreach($templateDisplayColumns as $columnName=>$columnSetting):?>
		        <td>
		        <?php if($columnName=='name'):?>
		        	<div class='item'><?php echo $element[$columnName];?></div>
		        <?php else:?>
						<?php echo $element[$columnName];?>
			    <?php endif;?>
		       </td>
		       <?php endforeach;?>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>