<?php echo $this->Navigation()->hengleike()->render(); ?>
<?php echo $this->Navigation()->Links()->render(); ?>

<div id='SlidePictureContainer'>
	
</div><!-- SlidePictureContainer end -->
<table id='ArticleColumnContainer' cellpadding='0' cellspacing='0'>
	<tr>
		<td>
			<ul class='ArticleColumnItem'>
				<li class='ArticleColumnItemLeft'>&nbsp;</li>
				<li class='ArticleColumnItemMiddle'>
					<ul class='titleContainer'>
						<li class='first'>
							<span class='ArticleColumnItemTitle'>康润新闻</span>
							<span class='ArticleColumnItemMore'>More</span>
						</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
					</ul>
				</li>
				<li class='ArticleColumnItemRight'>&nbsp;</li>
			</ul><!-- ul.ArticleColumnItem end -->
		</td>
		<td>
			<ul class='ArticleColumnItem'>
				<li class='ArticleColumnItemLeft'>&nbsp;</li>
				<li class='ArticleColumnItemMiddle'>
					<ul class='titleContainer'>
						<li class='first'>
							<span class='ArticleColumnItemTitle'>康润新闻</span>
							<span class='ArticleColumnItemMore'>More</span>
						</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
					</ul>
				</li>
				<li class='ArticleColumnItemRight'>&nbsp;</li>
			</ul><!-- ul.ArticleColumnItem end -->
		</td>
		<td>
			<ul class='ArticleColumnItem'>
				<li class='ArticleColumnItemLeft'>&nbsp;</li>
				<li class='ArticleColumnItemMiddle'>
					<ul class='titleContainer'>
						<li class='first'>
							<span class='ArticleColumnItemTitle'>康润新闻</span>
							<span class='ArticleColumnItemMore'>More</span>
						</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
						<li>测试标题测试标题测试标题测试标题测试标题</li>
					</ul>
				</li>
				<li class='ArticleColumnItemRight'>&nbsp;</li>
			</ul><!-- ul.ArticleColumnItem end -->
		</td>
	</tr>
</table><!-- ArticleColumnContainer end -->



