<ul class='article-list-control'>
	<?php if(isset($this->articleList)):?>
		<?php foreach($this->articleList as $article):?>					
			<li>
				<a href='<?php echo $article['href']?>' target='_blank'><?php echo $article['title']; ?></a>
				<?php if($this->articleTitleWithDate):?>
					<span class='date'><?php echo $article['date']; ?></span>
				<?php endif;?>
			</li>		
		<?php endforeach;?>	
	<?php endif;?>
</ul>